# Generated by Django 4.2.7 on 2026-01-28 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="edf_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["edf"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("patient_name", models.CharField(blank=True, max_length=255)),
                ("recording_date", models.DateTimeField(blank=True, null=True)),
                ("num_signals", models.IntegerField(default=0)),
                ("duration", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signal_label", models.CharField(max_length=255)),
                ("transducer", models.CharField(blank=True, max_length=255)),
                ("units", models.CharField(blank=True, max_length=50)),
                ("physical_min", models.FloatField()),
                ("physical_max", models.FloatField()),
                ("sampling_rate", models.FloatField()),
                (
                    "edf_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="viewer.edffile",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
