# Generated by Django 4.2.7 on 2026-01-28 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0002_signal_signal_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="edffile",
            name="hypnogram_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="edf_hypnogram/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["edf"]
                    )
                ],
            ),
        ),
    ]
